services:
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root_pass"
      MYSQL_DATABASE: "rewards"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql
    networks:
      - apiNetwork

volumes:
  db:
    driver: local

networks:
  apiNetwork:
    name: network