// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: rpc_add_activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityActionType int32

const (
	ActivityActionType_ActivityActionUnspecified ActivityActionType = 0
	ActivityActionType_ActivityInvite            ActivityActionType = 1
	ActivityActionType_ActivityAddReview         ActivityActionType = 2
)

// Enum value maps for ActivityActionType.
var (
	ActivityActionType_name = map[int32]string{
		0: "ActivityActionUnspecified",
		1: "ActivityInvite",
		2: "ActivityAddReview",
	}
	ActivityActionType_value = map[string]int32{
		"ActivityActionUnspecified": 0,
		"ActivityInvite":            1,
		"ActivityAddReview":         2,
	}
)

func (x ActivityActionType) Enum() *ActivityActionType {
	p := new(ActivityActionType)
	*p = x
	return p
}

func (x ActivityActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_add_activity_proto_enumTypes[0].Descriptor()
}

func (ActivityActionType) Type() protoreflect.EnumType {
	return &file_rpc_add_activity_proto_enumTypes[0]
}

func (x ActivityActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityActionType.Descriptor instead.
func (ActivityActionType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_add_activity_proto_rawDescGZIP(), []int{0}
}

type AddActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32              `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType ActivityActionType `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=ActivityActionType" json:"action_type,omitempty"`
}

func (x *AddActivityRequest) Reset() {
	*x = AddActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActivityRequest) ProtoMessage() {}

func (x *AddActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActivityRequest.ProtoReflect.Descriptor instead.
func (*AddActivityRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_activity_proto_rawDescGZIP(), []int{0}
}

func (x *AddActivityRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddActivityRequest) GetActionType() ActivityActionType {
	if x != nil {
		return x.ActionType
	}
	return ActivityActionType_ActivityActionUnspecified
}

type AddActivityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points float32 `protobuf:"fixed32,1,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *AddActivityResponse) Reset() {
	*x = AddActivityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_activity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActivityResponse) ProtoMessage() {}

func (x *AddActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_activity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActivityResponse.ProtoReflect.Descriptor instead.
func (*AddActivityResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_activity_proto_rawDescGZIP(), []int{1}
}

func (x *AddActivityResponse) GetPoints() float32 {
	if x != nil {
		return x.Points
	}
	return 0
}

var File_rpc_add_activity_proto protoreflect.FileDescriptor

var file_rpc_add_activity_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2d, 0x0a,
	0x13, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2a, 0x5e, 0x0a, 0x12,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x41, 0x64, 0x64, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_add_activity_proto_rawDescOnce sync.Once
	file_rpc_add_activity_proto_rawDescData = file_rpc_add_activity_proto_rawDesc
)

func file_rpc_add_activity_proto_rawDescGZIP() []byte {
	file_rpc_add_activity_proto_rawDescOnce.Do(func() {
		file_rpc_add_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_add_activity_proto_rawDescData)
	})
	return file_rpc_add_activity_proto_rawDescData
}

var file_rpc_add_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_add_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_activity_proto_goTypes = []interface{}{
	(ActivityActionType)(0),     // 0: ActivityActionType
	(*AddActivityRequest)(nil),  // 1: AddActivityRequest
	(*AddActivityResponse)(nil), // 2: AddActivityResponse
}
var file_rpc_add_activity_proto_depIdxs = []int32{
	0, // 0: AddActivityRequest.action_type:type_name -> ActivityActionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_add_activity_proto_init() }
func file_rpc_add_activity_proto_init() {
	if File_rpc_add_activity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_add_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_add_activity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddActivityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_add_activity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_activity_proto_goTypes,
		DependencyIndexes: file_rpc_add_activity_proto_depIdxs,
		EnumInfos:         file_rpc_add_activity_proto_enumTypes,
		MessageInfos:      file_rpc_add_activity_proto_msgTypes,
	}.Build()
	File_rpc_add_activity_proto = out.File
	file_rpc_add_activity_proto_rawDesc = nil
	file_rpc_add_activity_proto_goTypes = nil
	file_rpc_add_activity_proto_depIdxs = nil
}
