// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: rpc_spend_points.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpendActionType int32

const (
	SpendActionType_SpendActionUnspecified SpendActionType = 0
	SpendActionType_SpendPayService        SpendActionType = 3
	SpendActionType_SpendPayOtherService   SpendActionType = 4
)

// Enum value maps for SpendActionType.
var (
	SpendActionType_name = map[int32]string{
		0: "SpendActionUnspecified",
		3: "SpendPayService",
		4: "SpendPayOtherService",
	}
	SpendActionType_value = map[string]int32{
		"SpendActionUnspecified": 0,
		"SpendPayService":        3,
		"SpendPayOtherService":   4,
	}
)

func (x SpendActionType) Enum() *SpendActionType {
	p := new(SpendActionType)
	*p = x
	return p
}

func (x SpendActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpendActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_spend_points_proto_enumTypes[0].Descriptor()
}

func (SpendActionType) Type() protoreflect.EnumType {
	return &file_rpc_spend_points_proto_enumTypes[0]
}

func (x SpendActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpendActionType.Descriptor instead.
func (SpendActionType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_spend_points_proto_rawDescGZIP(), []int{0}
}

type SpendPointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int32           `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType   SpendActionType `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=SpendActionType" json:"action_type,omitempty"`
	ObjectId     int32           `protobuf:"varint,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	PointsAmount float32         `protobuf:"fixed32,4,opt,name=points_amount,json=pointsAmount,proto3" json:"points_amount,omitempty"`
}

func (x *SpendPointsRequest) Reset() {
	*x = SpendPointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_spend_points_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendPointsRequest) ProtoMessage() {}

func (x *SpendPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_spend_points_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendPointsRequest.ProtoReflect.Descriptor instead.
func (*SpendPointsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_spend_points_proto_rawDescGZIP(), []int{0}
}

func (x *SpendPointsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SpendPointsRequest) GetActionType() SpendActionType {
	if x != nil {
		return x.ActionType
	}
	return SpendActionType_SpendActionUnspecified
}

func (x *SpendPointsRequest) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *SpendPointsRequest) GetPointsAmount() float32 {
	if x != nil {
		return x.PointsAmount
	}
	return 0
}

type SpendPointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *SpendPointsResponse) Reset() {
	*x = SpendPointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_spend_points_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendPointsResponse) ProtoMessage() {}

func (x *SpendPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_spend_points_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendPointsResponse.ProtoReflect.Descriptor instead.
func (*SpendPointsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_spend_points_proto_rawDescGZIP(), []int{1}
}

func (x *SpendPointsResponse) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

var File_rpc_spend_points_proto protoreflect.FileDescriptor

var file_rpc_spend_points_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x53, 0x70, 0x65,
	0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x53, 0x70, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0c, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3c, 0x0a,
	0x13, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2a, 0x5c, 0x0a, 0x0f, 0x53,
	0x70, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x16, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x70,
	0x65, 0x6e, 0x64, 0x50, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x03, 0x12,
	0x18, 0x0a, 0x14, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x79, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x04, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_spend_points_proto_rawDescOnce sync.Once
	file_rpc_spend_points_proto_rawDescData = file_rpc_spend_points_proto_rawDesc
)

func file_rpc_spend_points_proto_rawDescGZIP() []byte {
	file_rpc_spend_points_proto_rawDescOnce.Do(func() {
		file_rpc_spend_points_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_spend_points_proto_rawDescData)
	})
	return file_rpc_spend_points_proto_rawDescData
}

var file_rpc_spend_points_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_spend_points_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_spend_points_proto_goTypes = []interface{}{
	(SpendActionType)(0),        // 0: SpendActionType
	(*SpendPointsRequest)(nil),  // 1: SpendPointsRequest
	(*SpendPointsResponse)(nil), // 2: SpendPointsResponse
	(*Activity)(nil),            // 3: Activity
}
var file_rpc_spend_points_proto_depIdxs = []int32{
	0, // 0: SpendPointsRequest.action_type:type_name -> SpendActionType
	3, // 1: SpendPointsResponse.activity:type_name -> Activity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_spend_points_proto_init() }
func file_rpc_spend_points_proto_init() {
	if File_rpc_spend_points_proto != nil {
		return
	}
	file_activity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_spend_points_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendPointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_spend_points_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendPointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_spend_points_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_spend_points_proto_goTypes,
		DependencyIndexes: file_rpc_spend_points_proto_depIdxs,
		EnumInfos:         file_rpc_spend_points_proto_enumTypes,
		MessageInfos:      file_rpc_spend_points_proto_msgTypes,
	}.Build()
	File_rpc_spend_points_proto = out.File
	file_rpc_spend_points_proto_rawDesc = nil
	file_rpc_spend_points_proto_goTypes = nil
	file_rpc_spend_points_proto_depIdxs = nil
}
